name: PR

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "gRPC"
      # This is done by a similar job defined in soundness.yml. It needs to be
      # separate in order to export an environment variable.
      api_breakage_check_enabled: false

  grpc-soundness:
    name: Soundness
    uses: ./.github/workflows/soundness.yml

  unit-tests:
    name: Unit tests
    uses: apple/swift-nio/.github/workflows/unit_tests.yml@main
    with:
      linux_5_9_enabled: false
      linux_5_10_enabled: false
      linux_6_0_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      linux_6_1_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      linux_nightly_next_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      linux_nightly_main_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"

  cxx-interop:
    name: Cxx interop
    uses: apple/swift-nio/.github/workflows/cxx_interop.yml@main
    with:
      linux_5_9_enabled: false
      linux_5_10_enabled: false

  static-sdk:
    name: Static SDK
    uses: apple/swift-nio/.github/workflows/static_sdk.yml@main
